-- ============================================================
-- Core Ontology Entity Tables (DDL)
-- Ontology: Supplier -> Part -> Plant -> Shipment -> Order -> Customer
-- Target: __SF_DATABASE__.__SF_SCHEMA__
-- ============================================================

USE DATABASE __SF_DATABASE__;
USE SCHEMA __SF_SCHEMA__;

CREATE OR REPLACE TABLE SUPPLIERS (
    SUPPLIER_ID         VARCHAR(10)    NOT NULL PRIMARY KEY,
    SUPPLIER_NAME       VARCHAR(100)   NOT NULL,
    COUNTRY             VARCHAR(50)    NOT NULL,
    REGION              VARCHAR(30)    NOT NULL,
    TIER                INT            NOT NULL,  -- 1=strategic, 2=preferred, 3=approved
    LEAD_TIME_DAYS      INT            NOT NULL,
    RELIABILITY_SCORE   DECIMAL(5,2)   NOT NULL,  -- 0-100
    ACTIVE              BOOLEAN        NOT NULL DEFAULT TRUE,
    CREATED_AT          TIMESTAMP_NTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE PARTS (
    PART_ID             VARCHAR(10)    NOT NULL PRIMARY KEY,
    PART_NAME           VARCHAR(100)   NOT NULL,
    CATEGORY            VARCHAR(50)    NOT NULL,
    SUBCATEGORY         VARCHAR(50),
    UNIT_OF_MEASURE     VARCHAR(10)    NOT NULL,
    STANDARD_COST       DECIMAL(12,2)  NOT NULL,
    WEIGHT_KG           DECIMAL(8,3),
    CRITICAL_FLAG       BOOLEAN        NOT NULL DEFAULT FALSE,
    CREATED_AT          TIMESTAMP_NTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE PLANTS (
    PLANT_ID            VARCHAR(10)    NOT NULL PRIMARY KEY,
    PLANT_NAME          VARCHAR(100)   NOT NULL,
    CITY                VARCHAR(50)    NOT NULL,
    COUNTRY             VARCHAR(50)    NOT NULL,
    REGION              VARCHAR(30)    NOT NULL,
    PLANT_TYPE          VARCHAR(30)    NOT NULL,  -- Manufacturing, Distribution, Assembly
    CAPACITY_UNITS      INT            NOT NULL,
    ACTIVE              BOOLEAN        NOT NULL DEFAULT TRUE,
    CREATED_AT          TIMESTAMP_NTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE CUSTOMERS (
    CUSTOMER_ID         VARCHAR(10)    NOT NULL PRIMARY KEY,
    CUSTOMER_NAME       VARCHAR(100)   NOT NULL,
    SEGMENT             VARCHAR(30)    NOT NULL,  -- Enterprise, Mid-Market, SMB
    INDUSTRY            VARCHAR(50)    NOT NULL,
    CITY                VARCHAR(50)    NOT NULL,
    COUNTRY             VARCHAR(50)    NOT NULL,
    REGION              VARCHAR(30)    NOT NULL,
    PRIORITY            VARCHAR(10)    NOT NULL,  -- High, Medium, Low
    CREATED_AT          TIMESTAMP_NTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE SUPPLIER_PARTS (
    SUPPLIER_ID         VARCHAR(10)    NOT NULL,
    PART_ID             VARCHAR(10)    NOT NULL,
    UNIT_PRICE          DECIMAL(12,2)  NOT NULL,
    MIN_ORDER_QTY       INT            NOT NULL,
    LEAD_TIME_DAYS      INT            NOT NULL,
    CONTRACT_START      DATE           NOT NULL,
    CONTRACT_END        DATE,
    PRIMARY KEY (SUPPLIER_ID, PART_ID),
    FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIERS(SUPPLIER_ID),
    FOREIGN KEY (PART_ID)     REFERENCES PARTS(PART_ID)
);

CREATE OR REPLACE TABLE PLANT_INVENTORY (
    PLANT_ID            VARCHAR(10)    NOT NULL,
    PART_ID             VARCHAR(10)    NOT NULL,
    SNAPSHOT_DATE       DATE           NOT NULL,
    ON_HAND_QTY         INT            NOT NULL,
    SAFETY_STOCK_QTY    INT            NOT NULL,
    REORDER_POINT       INT            NOT NULL,
    AVG_DAILY_USAGE     DECIMAL(10,2)  NOT NULL,
    PRIMARY KEY (PLANT_ID, PART_ID, SNAPSHOT_DATE),
    FOREIGN KEY (PLANT_ID) REFERENCES PLANTS(PLANT_ID),
    FOREIGN KEY (PART_ID)  REFERENCES PARTS(PART_ID)
);

CREATE OR REPLACE TABLE PURCHASE_ORDERS (
    PO_ID               VARCHAR(12)    NOT NULL PRIMARY KEY,
    SUPPLIER_ID         VARCHAR(10)    NOT NULL,
    PLANT_ID            VARCHAR(10)    NOT NULL,
    PART_ID             VARCHAR(10)    NOT NULL,
    ORDER_DATE          DATE           NOT NULL,
    PROMISED_DATE       DATE           NOT NULL,
    RECEIVED_DATE       DATE,
    ORDERED_QTY         INT            NOT NULL,
    RECEIVED_QTY        INT,
    UNIT_COST           DECIMAL(12,2)  NOT NULL,
    FREIGHT_COST        DECIMAL(10,2)  NOT NULL DEFAULT 0,
    DUTY_COST           DECIMAL(10,2)  NOT NULL DEFAULT 0,
    HANDLING_COST       DECIMAL(10,2)  NOT NULL DEFAULT 0,
    STATUS              VARCHAR(20)    NOT NULL,  -- Open, Received, Partial, Cancelled
    FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIERS(SUPPLIER_ID),
    FOREIGN KEY (PLANT_ID)    REFERENCES PLANTS(PLANT_ID),
    FOREIGN KEY (PART_ID)     REFERENCES PARTS(PART_ID)
);

CREATE OR REPLACE TABLE SALES_ORDERS (
    ORDER_ID            VARCHAR(12)    NOT NULL PRIMARY KEY,
    CUSTOMER_ID         VARCHAR(10)    NOT NULL,
    ORDER_DATE          DATE           NOT NULL,
    REQUESTED_DATE      DATE           NOT NULL,
    STATUS              VARCHAR(20)    NOT NULL,  -- Open, Shipped, Delivered, Cancelled
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);

CREATE OR REPLACE TABLE ORDER_LINES (
    ORDER_ID            VARCHAR(12)    NOT NULL,
    LINE_NUM            INT            NOT NULL,
    PART_ID             VARCHAR(10)    NOT NULL,
    PLANT_ID            VARCHAR(10)    NOT NULL,
    ORDERED_QTY         INT            NOT NULL,
    FULFILLED_QTY       INT            NOT NULL DEFAULT 0,
    UNIT_PRICE          DECIMAL(12,2)  NOT NULL,
    LINE_STATUS         VARCHAR(20)    NOT NULL,  -- Open, Fulfilled, Partial, Cancelled
    PRIMARY KEY (ORDER_ID, LINE_NUM),
    FOREIGN KEY (ORDER_ID) REFERENCES SALES_ORDERS(ORDER_ID),
    FOREIGN KEY (PART_ID)  REFERENCES PARTS(PART_ID),
    FOREIGN KEY (PLANT_ID) REFERENCES PLANTS(PLANT_ID)
);

CREATE OR REPLACE TABLE SHIPMENTS (
    SHIPMENT_ID         VARCHAR(12)    NOT NULL PRIMARY KEY,
    ORDER_ID            VARCHAR(12)    NOT NULL,
    PLANT_ID            VARCHAR(10)    NOT NULL,
    CUSTOMER_ID         VARCHAR(10)    NOT NULL,
    SHIP_DATE           DATE           NOT NULL,
    PROMISED_DELIVERY   DATE           NOT NULL,
    ACTUAL_DELIVERY     DATE,
    CARRIER             VARCHAR(50)    NOT NULL,
    TRANSPORT_MODE      VARCHAR(20)    NOT NULL,  -- Truck, Rail, Air, Ocean
    FREIGHT_COST        DECIMAL(10,2)  NOT NULL,
    STATUS              VARCHAR(20)    NOT NULL,  -- In Transit, Delivered, Delayed
    FOREIGN KEY (ORDER_ID)    REFERENCES SALES_ORDERS(ORDER_ID),
    FOREIGN KEY (PLANT_ID)    REFERENCES PLANTS(PLANT_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);

CREATE OR REPLACE TABLE SHIPMENT_LINES (
    SHIPMENT_ID         VARCHAR(12)    NOT NULL,
    LINE_NUM            INT            NOT NULL,
    PART_ID             VARCHAR(10)    NOT NULL,
    SHIPPED_QTY         INT            NOT NULL,
    PRIMARY KEY (SHIPMENT_ID, LINE_NUM),
    FOREIGN KEY (SHIPMENT_ID) REFERENCES SHIPMENTS(SHIPMENT_ID),
    FOREIGN KEY (PART_ID)     REFERENCES PARTS(PART_ID)
);

