-- ============================================================
-- Metric Views - Canonical Supply Chain KPIs
-- V_ON_TIME_DELIVERY:     Supplier OTD (88.24%)
-- V_FILL_RATE:            Customer Fill Rate (91.72%)
-- V_DAYS_OF_INVENTORY:    DOI (23.2 days)
-- V_LANDED_COST:          Landed Cost per Unit
-- V_SHIPMENT_OTD:         Delivery OTD (83.56%)
-- V_SCM_EXECUTIVE_SUMMARY: Cross-domain monthly scorecard
-- ============================================================

USE DATABASE __SF_DATABASE__;
USE SCHEMA __SF_SCHEMA__;

-- Metric Views for canonical SCM KPIs
-- ============================================================

-- On-Time Delivery (OTD) by supplier, plant, customer, period
CREATE OR REPLACE VIEW V_ON_TIME_DELIVERY AS
SELECT
    po.SUPPLIER_ID,
    s.SUPPLIER_NAME,
    po.PLANT_ID,
    pl.PLANT_NAME,
    DATE_TRUNC('month', po.ORDER_DATE) AS ORDER_MONTH,
    COUNT(*) AS TOTAL_POS,
    SUM(CASE WHEN po.STATUS = 'Received' AND po.RECEIVED_DATE <= po.PROMISED_DATE THEN 1 ELSE 0 END) AS ON_TIME_POS,
    ROUND(ON_TIME_POS * 100.0 / NULLIF(TOTAL_POS, 0), 2) AS OTD_PCT
FROM PURCHASE_ORDERS po
JOIN SUPPLIERS s ON po.SUPPLIER_ID = s.SUPPLIER_ID
JOIN PLANTS pl ON po.PLANT_ID = pl.PLANT_ID
WHERE po.STATUS NOT IN ('Open', 'Cancelled')
GROUP BY 1,2,3,4,5;

-- Fill Rate by order, plant, customer, period
CREATE OR REPLACE VIEW V_FILL_RATE AS
SELECT
    so.CUSTOMER_ID,
    c.CUSTOMER_NAME,
    c.SEGMENT,
    ol.PLANT_ID,
    pl.PLANT_NAME,
    DATE_TRUNC('month', so.ORDER_DATE) AS ORDER_MONTH,
    SUM(ol.ORDERED_QTY) AS TOTAL_ORDERED,
    SUM(ol.FULFILLED_QTY) AS TOTAL_FULFILLED,
    ROUND(TOTAL_FULFILLED * 100.0 / NULLIF(TOTAL_ORDERED, 0), 2) AS FILL_RATE_PCT
FROM SALES_ORDERS so
JOIN ORDER_LINES ol ON so.ORDER_ID = ol.ORDER_ID
JOIN CUSTOMERS c ON so.CUSTOMER_ID = c.CUSTOMER_ID
JOIN PLANTS pl ON ol.PLANT_ID = pl.PLANT_ID
WHERE so.STATUS NOT IN ('Cancelled')
GROUP BY 1,2,3,4,5,6;

-- Days of Inventory (DOI) by plant, part, snapshot
CREATE OR REPLACE VIEW V_DAYS_OF_INVENTORY AS
SELECT
    pi.PLANT_ID,
    pl.PLANT_NAME,
    pi.PART_ID,
    pt.PART_NAME,
    pt.CATEGORY,
    pi.SNAPSHOT_DATE,
    pi.ON_HAND_QTY,
    pi.SAFETY_STOCK_QTY,
    pi.AVG_DAILY_USAGE,
    ROUND(pi.ON_HAND_QTY / NULLIF(pi.AVG_DAILY_USAGE, 0), 1) AS DAYS_OF_INVENTORY,
    CASE
        WHEN pi.ON_HAND_QTY < pi.SAFETY_STOCK_QTY THEN 'Below Safety Stock'
        WHEN pi.ON_HAND_QTY < pi.REORDER_POINT THEN 'Reorder Required'
        ELSE 'Adequate'
    END AS INVENTORY_STATUS
FROM PLANT_INVENTORY pi
JOIN PLANTS pl ON pi.PLANT_ID = pl.PLANT_ID
JOIN PARTS pt ON pi.PART_ID = pt.PART_ID;

-- Landed Cost by PO (unit cost + freight + duty + handling)
CREATE OR REPLACE VIEW V_LANDED_COST AS
SELECT
    po.PO_ID,
    po.SUPPLIER_ID,
    s.SUPPLIER_NAME,
    s.COUNTRY AS SUPPLIER_COUNTRY,
    po.PLANT_ID,
    pl.PLANT_NAME,
    po.PART_ID,
    pt.PART_NAME,
    po.ORDER_DATE,
    DATE_TRUNC('month', po.ORDER_DATE) AS ORDER_MONTH,
    po.ORDERED_QTY,
    po.UNIT_COST,
    po.ORDERED_QTY * po.UNIT_COST AS MATERIAL_COST,
    po.FREIGHT_COST,
    po.DUTY_COST,
    po.HANDLING_COST,
    (po.ORDERED_QTY * po.UNIT_COST) + po.FREIGHT_COST + po.DUTY_COST + po.HANDLING_COST AS TOTAL_LANDED_COST,
    ROUND(((po.ORDERED_QTY * po.UNIT_COST) + po.FREIGHT_COST + po.DUTY_COST + po.HANDLING_COST) / NULLIF(po.ORDERED_QTY, 0), 2) AS LANDED_COST_PER_UNIT
FROM PURCHASE_ORDERS po
JOIN SUPPLIERS s ON po.SUPPLIER_ID = s.SUPPLIER_ID
JOIN PLANTS pl ON po.PLANT_ID = pl.PLANT_ID
JOIN PARTS pt ON po.PART_ID = pt.PART_ID
WHERE po.STATUS != 'Cancelled';

-- Shipment OTD (customer-facing delivery performance)
CREATE OR REPLACE VIEW V_SHIPMENT_OTD AS
SELECT
    sh.CUSTOMER_ID,
    c.CUSTOMER_NAME,
    c.SEGMENT,
    sh.PLANT_ID,
    pl.PLANT_NAME,
    sh.CARRIER,
    sh.TRANSPORT_MODE,
    DATE_TRUNC('month', sh.SHIP_DATE) AS SHIP_MONTH,
    COUNT(*) AS TOTAL_SHIPMENTS,
    SUM(CASE WHEN sh.STATUS = 'Delivered' AND sh.ACTUAL_DELIVERY <= sh.PROMISED_DELIVERY THEN 1 ELSE 0 END) AS ON_TIME_DELIVERIES,
    ROUND(ON_TIME_DELIVERIES * 100.0 / NULLIF(TOTAL_SHIPMENTS, 0), 2) AS DELIVERY_OTD_PCT
FROM SHIPMENTS sh
JOIN CUSTOMERS c ON sh.CUSTOMER_ID = c.CUSTOMER_ID
JOIN PLANTS pl ON sh.PLANT_ID = pl.PLANT_ID
WHERE sh.STATUS != 'In Transit'
GROUP BY 1,2,3,4,5,6,7,8;

-- ============================================================
-- Summary: Cross-domain unified metrics view
-- ============================================================

CREATE OR REPLACE VIEW V_SCM_EXECUTIVE_SUMMARY AS
WITH otd_agg AS (
    SELECT ORDER_MONTH, AVG(OTD_PCT) AS AVG_SUPPLIER_OTD FROM V_ON_TIME_DELIVERY GROUP BY 1
),
fill_agg AS (
    SELECT ORDER_MONTH, AVG(FILL_RATE_PCT) AS AVG_FILL_RATE FROM V_FILL_RATE GROUP BY 1
),
doi_agg AS (
    SELECT DATE_TRUNC('month', SNAPSHOT_DATE) AS SNAPSHOT_MONTH, AVG(DAYS_OF_INVENTORY) AS AVG_DOI
    FROM V_DAYS_OF_INVENTORY GROUP BY 1
),
cost_agg AS (
    SELECT ORDER_MONTH, AVG(LANDED_COST_PER_UNIT) AS AVG_LANDED_COST_PER_UNIT, SUM(TOTAL_LANDED_COST) AS TOTAL_LANDED_COST
    FROM V_LANDED_COST GROUP BY 1
),
ship_agg AS (
    SELECT SHIP_MONTH AS ORDER_MONTH, AVG(DELIVERY_OTD_PCT) AS AVG_DELIVERY_OTD FROM V_SHIPMENT_OTD GROUP BY 1
)
SELECT
    COALESCE(o.ORDER_MONTH, f.ORDER_MONTH, d.SNAPSHOT_MONTH, c.ORDER_MONTH, s.ORDER_MONTH) AS PERIOD,
    o.AVG_SUPPLIER_OTD,
    s.AVG_DELIVERY_OTD,
    f.AVG_FILL_RATE,
    d.AVG_DOI AS AVG_DAYS_OF_INVENTORY,
    c.AVG_LANDED_COST_PER_UNIT,
    c.TOTAL_LANDED_COST
FROM otd_agg o
FULL OUTER JOIN fill_agg f ON o.ORDER_MONTH = f.ORDER_MONTH
FULL OUTER JOIN doi_agg d ON o.ORDER_MONTH = d.SNAPSHOT_MONTH
FULL OUTER JOIN cost_agg c ON o.ORDER_MONTH = c.ORDER_MONTH
FULL OUTER JOIN ship_agg s ON o.ORDER_MONTH = s.ORDER_MONTH
ORDER BY PERIOD;
